# Generated by Django on initial setup for StoredFile and ExecutionRun models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('swagger', 'Swagger JSON'), ('testcase', 'Test Case Excel'), ('result', 'Result Excel')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('content', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('size_bytes', models.IntegerField(default=0)),
            ],
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.CreateModel(
            name='ExecutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs_as_result', to='api.storedfile')),
                ('swagger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs_as_swagger', to='api.storedfile')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs_as_testcase', to='api.storedfile')),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
